In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [50]:
path_to_data = '/content/drive/MyDrive/Minerals_classification/csv_table.csv'
df = pd.read_csv(path_to_data, sep=';')
df

color streak lustre transparency  cleavage mohs_hardness    density  \
0           7      7      1            3         6         2.5-3      19.32   
1        5;12   5;12      1            3         6         2.5-3       8.92   
2         2;3    2;3      6            3         2             1  2.08-2.23   
3           7      7    3;6            3         4           1-2      2.070   
4      1;3;13      1    3;8          1;2         3         2.5-3       6.36   
..        ...    ...    ...          ...       ...           ...        ...   
373     10;11      1      2          2;3         4         7-7.5  2.76-2.78   
374  2;4;5;12      4      2          2;3         6             5  2.38-2.71   
375  4;5;7;12      1    2;8          1;2         4         5-5.5    2.8-3.1   
376         8   8;10    2;8        1;2;3         2             5  3.28-3.35   
377       2;4    3;8    2;8            3         2         5.5-6  3.19-3.56   

    fracture  group  
0          4      8  
1          4      8  
2          6      8  
3          6      8  
4          2      6  
..       ...    ...  
373      2;3      1  
374      2;6      1  
375        2      1  
376    2;3;6      1  
377      2;6      1  

[378 rows x 9 columns]

In [51]:
df = df.sample(frac=1).reset_index(drop=True)
df

color streak lustre transparency  cleavage mohs_hardness    density  \
0    9;10;12;13      1      2        1;2;3         6             4       2.28   
1             2      2      1            3         6         8-9.0       4.87   
2             9      1      2            1         4         7.5-8   2.68-2.8   
3             1      3      1            3         3           6-7      10.78   
4          2;10    4;8    2;5            2         2             6        3.4   
..          ...    ...    ...          ...       ...           ...        ...   
373      1;3;12      1    2;4          1;2         2           5-6        2.9   
374       3;7;8    3;8  2;4;8            3         3         2.5-3      3-3.4   
375   1;3;6;7;8      1  2;3;6          1;2         5         3.5-4       7.04   
376         1;3      1      2          1;2         2         6-6.5      2.760   
377         1;4      5      2            3         3         6-6.5  4.72-4.83   

    fracture  group  
0        2;6      2  
1        2;6      4  
2        2;6      1  
3          3      5  
4        2;6      1  
..       ...    ...  
373      2;6      1  
374        2      1  
375      2;6      2  
376      2;6      1  
377        2      1  

[378 rows x 9 columns]

In [52]:
print(df.dtypes)

color            object
streak           object
lustre           object
transparency     object
cleavage          int64
mohs_hardness    object
density          object
fracture         object
group             int64
dtype: object


In [53]:
df['color'] = df['color'].apply(lambda x: list(map(int, x.split(';'))))
df['streak'] = df['streak'].apply(lambda x: list(map(int, x.split(';'))))
df['lustre'] = df['lustre'].apply(lambda x: list(map(int, x.split(';'))))
df['transparency'] = df['transparency'].apply(lambda x: list(map(int, x.split(';'))))
df['fracture'] = df['fracture'].apply(lambda x: list(map(int, x.split(';'))))

In [54]:
df

color  streak     lustre transparency  cleavage mohs_hardness  \
0    [9, 10, 12, 13]     [1]        [2]    [1, 2, 3]         6             4   
1                [2]     [2]        [1]          [3]         6         8-9.0   
2                [9]     [1]        [2]          [1]         4         7.5-8   
3                [1]     [3]        [1]          [3]         3           6-7   
4            [2, 10]  [4, 8]     [2, 5]          [2]         2             6   
..               ...     ...        ...          ...       ...           ...   
373       [1, 3, 12]     [1]     [2, 4]       [1, 2]         2           5-6   
374        [3, 7, 8]  [3, 8]  [2, 4, 8]          [3]         3         2.5-3   
375  [1, 3, 6, 7, 8]     [1]  [2, 3, 6]       [1, 2]         5         3.5-4   
376           [1, 3]     [1]        [2]       [1, 2]         2         6-6.5   
377           [1, 4]     [5]        [2]          [3]         3         6-6.5   

       density fracture  group  
0         2.28   [2, 6]      2  
1         4.87   [2, 6]      4  
2     2.68-2.8   [2, 6]      1  
3        10.78      [3]      5  
4          3.4   [2, 6]      1  
..         ...      ...    ...  
373        2.9   [2, 6]      1  
374      3-3.4      [2]      1  
375       7.04   [2, 6]      2  
376      2.760   [2, 6]      1  
377  4.72-4.83      [2]      1  

[378 rows x 9 columns]

In [55]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

In [56]:
color_encoded = pd.DataFrame(mlb.fit_transform(df['color']), columns=[f'color_{cls}' for cls in mlb.classes_])
df=df.join(color_encoded)

streak_encoded = pd.DataFrame(mlb.fit_transform(df['streak']), columns=[f'streak_{cls}' for cls in mlb.classes_])
df=df.join(streak_encoded)

lustre_encoded = pd.DataFrame(mlb.fit_transform(df['lustre']), columns=[f'lustre_{cls}' for cls in mlb.classes_])
df=df.join(lustre_encoded)

transparency_encoded = pd.DataFrame(mlb.fit_transform(df['transparency']), columns=[f'transparency_{cls}' for cls in mlb.classes_])
df=df.join(transparency_encoded)

fracture_encoded = pd.DataFrame(mlb.fit_transform(df['fracture']), columns=[f'fracture_{cls}' for cls in mlb.classes_])
df=df.join(fracture_encoded)


In [57]:
df.drop(['color', 'streak', 'lustre', 'transparency', 'fracture'], axis=1, inplace=True)

df

cleavage mohs_hardness    density  group  color_1  color_2  color_3  \
0           6             4       2.28      2        0        0        0   
1           6         8-9.0       4.87      4        0        1        0   
2           4         7.5-8   2.68-2.8      1        0        0        0   
3           3           6-7      10.78      5        1        0        0   
4           2             6        3.4      1        0        1        0   
..        ...           ...        ...    ...      ...      ...      ...   
373         2           5-6        2.9      1        1        0        1   
374         3         2.5-3      3-3.4      1        0        0        1   
375         5         3.5-4       7.04      2        1        0        1   
376         2         6-6.5      2.760      1        1        0        1   
377         3         6-6.5  4.72-4.83      1        1        0        0   

     color_4  color_5  color_6  ...  transparency_2  transparency_3  \
0          0        0        0  ...               1               1   
1          0        0        0  ...               0               1   
2          0        0        0  ...               0               0   
3          0        0        0  ...               0               1   
4          0        0        0  ...               1               0   
..       ...      ...      ...  ...             ...             ...   
373        0        0        0  ...               1               0   
374        0        0        0  ...               0               1   
375        0        0        1  ...               1               0   
376        0        0        0  ...               1               0   
377        1        0        0  ...               0               1   

     fracture_1  fracture_2  fracture_3  fracture_4  fracture_5  fracture_6  \
0             0           1           0           0           0           1   
1             0           1           0           0           0           1   
2             0           1           0           0           0           1   
3             0           0           1           0           0           0   
4             0           1           0           0           0           1   
..          ...         ...         ...         ...         ...         ...   
373           0           1           0           0           0           1   
374           0           1           0           0           0           0   
375           0           1           0           0           0           1   
376           0           1           0           0           0           1   
377           0           1           0           0           0           0   

     fracture_7  fracture_8  
0             0           0  
1             0           0  
2             0           0  
3             0           0  
4             0           0  
..          ...         ...  
373           0           0  
374           0           0  
375           0           0  
376           0           0  
377           0           0  

[378 rows x 49 columns]

In [58]:
class NumericRange:
    def __init__(self, start, end=None):
        self.start = float(start)
        self.end = float(end) if end is not None else self.start
        self.mean = (self.start + self.end) / 2
        self.range = self.end - self.start

    def __repr__(self):
        return f'{self.start}-{self.end}' if self.start != self.end else str(self.start)

def parse_numeric_range(value):
    parts = value.split('-')
    if len(parts) == 2:
        return NumericRange(parts[0], parts[1])
    else:
        return NumericRange(parts[0])

df['mohs_hardness'] = df['mohs_hardness'].apply(parse_numeric_range)

df['mohs_hardness_start'] = df['mohs_hardness'].apply(lambda x: x.start)
df['mohs_hardness_end'] = df['mohs_hardness'].apply(lambda x: x.end)
df['mohs_hardness_mean'] = df['mohs_hardness'].apply(lambda x: x.mean)
df['mohs_hardness_range'] = df['mohs_hardness'].apply(lambda x: x.range)

df.drop('mohs_hardness', axis=1, inplace=True)

df['density'] = df['density'].apply(parse_numeric_range)

df['density_start'] = df['density'].apply(lambda x: x.start)
df['density_end'] = df['density'].apply(lambda x: x.end)
df['density_mean'] = df['density'].apply(lambda x: x.mean)
df['density_range'] = df['density'].apply(lambda x: x.range)

df.drop('density', axis=1, inplace=True)

In [60]:
column_to_move = 'group'
col = df.pop(column_to_move)
df.insert(len(df.columns), column_to_move, col)

In [61]:
df

cleavage  color_1  color_2  color_3  color_4  color_5  color_6  color_7  \
0           6        0        0        0        0        0        0        0   
1           6        0        1        0        0        0        0        0   
2           4        0        0        0        0        0        0        0   
3           3        1        0        0        0        0        0        0   
4           2        0        1        0        0        0        0        0   
..        ...      ...      ...      ...      ...      ...      ...      ...   
373         2        1        0        1        0        0        0        0   
374         3        0        0        1        0        0        0        1   
375         5        1        0        1        0        0        1        1   
376         2        1        0        1        0        0        0        0   
377         3        1        0        0        1        0        0        0   

     color_8  color_9  ...  fracture_8  mohs_hardness_start  \
0          0        1  ...           0                  4.0   
1          0        0  ...           0                  8.0   
2          0        1  ...           0                  7.5   
3          0        0  ...           0                  6.0   
4          0        0  ...           0                  6.0   
..       ...      ...  ...         ...                  ...   
373        0        0  ...           0                  5.0   
374        1        0  ...           0                  2.5   
375        1        0  ...           0                  3.5   
376        0        0  ...           0                  6.0   
377        0        0  ...           0                  6.0   

     mohs_hardness_end  mohs_hardness_mean  mohs_hardness_range  \
0                  4.0                4.00                  0.0   
1                  9.0                8.50                  1.0   
2                  8.0                7.75                  0.5   
3                  7.0                6.50                  1.0   
4                  6.0                6.00                  0.0   
..                 ...                 ...                  ...   
373                6.0                5.50                  1.0   
374                3.0                2.75                  0.5   
375                4.0                3.75                  0.5   
376                6.5                6.25                  0.5   
377                6.5                6.25                  0.5   

     density_start  density_end  density_mean  density_range  group  
0             2.28         2.28         2.280           0.00      2  
1             4.87         4.87         4.870           0.00      4  
2             2.68         2.80         2.740           0.12      1  
3            10.78        10.78        10.780           0.00      5  
4             3.40         3.40         3.400           0.00      1  
..             ...          ...           ...            ...    ...  
373           2.90         2.90         2.900           0.00      1  
374           3.00         3.40         3.200           0.40      1  
375           7.04         7.04         7.040           0.00      2  
376           2.76         2.76         2.760           0.00      1  
377           4.72         4.83         4.775           0.11      1  

[378 rows x 55 columns]

In [62]:
print(df.dtypes)

cleavage                 int64
color_1                  int64
color_2                  int64
color_3                  int64
color_4                  int64
color_5                  int64
color_6                  int64
color_7                  int64
color_8                  int64
color_9                  int64
color_10                 int64
color_11                 int64
color_12                 int64
color_13                 int64
streak_1                 int64
streak_2                 int64
streak_3                 int64
streak_4                 int64
streak_5                 int64
streak_6                 int64
streak_7                 int64
streak_8                 int64
streak_9                 int64
streak_10                int64
streak_11                int64
streak_12                int64
streak_13                int64
lustre_1                 int64
lustre_2                 int64
lustre_3                 int64
lustre_4                 int64
lustre_5                 int64
lustre_6

In [64]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['group'])
y = df['group']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_test, X_valid, y_test, y_valid = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)
valid_df = pd.concat([X_valid, y_valid], axis=1)


In [66]:
train_df.shape

(302, 55)

In [67]:
test_df.shape

(38, 55)

In [68]:
valid_df.shape

(38, 55)

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [71]:
model.coef_

array([[-3.24176563e-01, -1.14321080e-01, -7.27623004e-02,
        -3.34390452e-01,  3.01588982e-01, -3.28040706e-01,
         6.70041547e-01, -3.17275440e-01,  6.44592883e-01,
        -3.35489077e-01, -5.37230872e-02,  9.35659719e-02,
         7.10094715e-03, -5.71887110e-01,  1.09963926e-01,
         1.91292865e-02, -4.38365492e-01,  8.11976138e-01,
         1.06687294e-01, -3.71127653e-01, -5.49121362e-01,
         1.66254701e-01,  2.20814742e-01, -1.10227397e-01,
         0.00000000e+00,  4.09290065e-01, -3.26100679e-01,
        -4.14473836e-01, -2.17065482e-01, -3.16884540e-01,
         3.76613593e-01,  2.91656286e-01,  5.43110347e-01,
        -1.97273823e-01, -3.97709135e-01,  4.20676617e-01,
         8.03210780e-01,  4.42228053e-01, -4.30622882e-01,
         4.06566267e-01, -6.83970710e-01, -2.29431686e-01,
         1.75014067e-01, -5.78778747e-01,  0.00000000e+00,
         1.39527159e+00,  3.06116385e-01,  4.04757250e-01,
         3.55436817e-01,  9.86408641e-02, -8.60060486e-0

In [72]:
model.intercept_

array([ 3.05650607, -0.76483681, -0.09847885, -2.93321968,  0.18496983,
        0.14111337,  0.78185173, -0.36790567])

In [73]:
y_test

172    3
145    1
113    2
104    1
365    7
177    1
340    1
46     5
163    4
45     6
30     5
110    8
360    2
361    5
22     1
25     1
326    5
76     3
73     1
355    8
242    1
208    1
210    3
316    1
114    4
247    1
374    1
116    1
329    5
310    1
141    1
323    1
0      2
15     1
225    5
227    1
366    1
237    1
Name: group, dtype: int64

In [75]:
model.predict(X_train)

array([1, 1, 1, 1, 5, 1, 4, 3, 1, 5, 8, 1, 1, 2, 1, 1, 4, 1, 5, 1, 7, 4,
       1, 1, 5, 1, 1, 5, 5, 1, 5, 3, 1, 1, 1, 1, 1, 1, 1, 1, 7, 1, 4, 1,
       1, 4, 1, 6, 2, 1, 2, 1, 1, 3, 3, 1, 4, 6, 3, 1, 5, 4, 4, 1, 7, 1,
       1, 2, 1, 1, 4, 5, 1, 5, 1, 5, 8, 4, 1, 5, 1, 1, 1, 8, 1, 6, 1, 1,
       1, 5, 4, 1, 1, 1, 1, 8, 6, 1, 1, 1, 5, 3, 1, 8, 1, 1, 5, 6, 5, 1,
       1, 5, 5, 1, 1, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 5, 1, 2, 8, 1, 1, 5, 3, 1, 5, 4, 4, 1, 1, 1, 4,
       1, 1, 1, 1, 1, 7, 4, 1, 3, 1, 4, 4, 5, 8, 1, 7, 1, 1, 8, 1, 5, 4,
       5, 1, 1, 1, 1, 3, 1, 1, 3, 1, 5, 1, 5, 1, 4, 1, 5, 5, 1, 1, 6, 1,
       4, 4, 1, 4, 1, 4, 4, 1, 1, 1, 2, 7, 4, 4, 1, 4, 5, 5, 2, 1, 1, 1,
       1, 1, 4, 5, 1, 1, 1, 1, 1, 1, 4, 5, 1, 5, 1, 1, 1, 4, 8, 1, 1, 1,
       4, 1, 5, 4, 1, 4, 1, 1, 4, 1, 1, 1, 3, 1, 1, 2, 1, 1, 1, 4, 1, 5,
       3, 7, 1, 3, 2, 1, 1, 3, 2, 1, 1, 1, 3, 2, 1, 3, 5, 4, 1, 1, 4, 4,
       1, 1, 8, 1, 1, 8, 5, 1, 1, 4, 1, 3, 5, 1, 1,

In [87]:
(model.predict(X_valid)==y_valid).mean()

0.8421052631578947

In [90]:
y_valid

55     1
39     4
292    4
287    5
77     3
56     2
3      5
290    1
118    1
9      1
84     1
63     1
338    1
33     8
72     1
42     1
148    1
93     1
78     1
173    4
229    4
232    1
124    1
253    5
246    1
5      1
140    1
82     3
376    1
245    1
182    4
57     1
305    5
108    4
238    1
192    5
31     5
90     4
Name: group, dtype: int64

In [89]:
model.predict(X_valid)

array([1, 1, 4, 5, 2, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 4, 4, 1,
       1, 5, 1, 1, 1, 1, 1, 1, 4, 1, 5, 4, 1, 5, 4, 4])

In [88]:
model.decision_function(X_valid)

array([[ 2.67784749e+00,  1.70073822e+00,  1.02574170e+00,
        -1.37674417e+00, -1.27724007e+00,  1.08911609e+00,
        -6.36286518e-01, -3.20317275e+00],
       [ 7.93535394e+00,  1.21922305e+00, -8.81734641e-01,
         4.07160773e+00, -3.15767269e+00, -2.88784199e+00,
        -9.38149735e-01, -5.36078567e+00],
       [ 1.05431683e+00,  1.21188800e+00, -2.06796424e+00,
         7.01446221e+00,  1.18133426e+00, -4.50014738e+00,
        -2.93581375e+00, -9.58075920e-01],
       [-7.10046666e-01, -1.63947929e+00,  3.57516057e-01,
        -1.62452311e+00,  2.95708860e+00, -5.39417371e-01,
         7.13625126e-01,  4.85236654e-01],
       [ 1.44885120e+00,  2.67722617e+00,  7.56945439e-01,
        -9.56817631e-02, -8.34191433e-01,  8.44063490e-01,
        -2.72373569e+00, -2.07347741e+00],
       [ 4.05812252e+00,  1.25086466e+00, -9.16688170e-01,
         2.35336801e+00, -2.76902655e+00, -5.64113979e-01,
         1.53916929e-01, -3.56644341e+00],
       [-6.40250536e+00, -8.316710

In [91]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, make_scorer

In [94]:
accuracy = accuracy_score(y_valid, model.predict(X_valid))
precision = precision_score(y_valid, model.predict(X_valid), average='weighted')
recall = recall_score(y_valid, model.predict(X_valid), average='weighted')
f1 = f1_score(y_valid, model.predict(X_valid), average='weighted')

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-score: {f1}')

Accuracy: 0.9210526315789473
Precision: 0.8782894736842105
Recall: 0.9210526315789473
F1-score: 0.8963562753036437


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [93]:
X_test_valid = pd.concat([X_test, X_valid], axis=0)
y_test_valid = pd.concat([y_test, y_valid], axis=0)

model.fit(X_test_valid, y_test_valid)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [95]:
import pickle

In [96]:
model_file_path = '/content/drive/MyDrive/Minerals_classification/lr_model_mineral_group_prediction.sav'
pickle.dump(model, open(model_file_path, 'wb'))
